
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.stream.IntStream;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.ConcurrentLinkedQueue;

public class Exercise16 {
	/*
	 * - From Exercise15, use submit(Callable) at the executor to get a Future
	 *   that returns a result. The result should be the sum of the numbers
	 *   generated by the producer in that specific product.
	 * - Put all the futures in a shared list (remember about thread-safety!).
	 * - When the main thread is done waiting for both producers and consumers
	 *   to terminate, print out the results in the futures in the shared list.
	 */

	private static class Product {
		private final List<Integer> list;
		public Product (List<Integer> list) {
			this.list = list;
		}

		public Integer sum() {
			return list.stream().mapToInt(Integer::intValue).sum();
		}
	}

	private static final int NUM_THREADS = 4;
	private static final ConcurrentLinkedQueue<Future<Integer>> futures = new ConcurrentLinkedQueue<>();
	private static final ExecutorService exec = Executors.newFixedThreadPool(NUM_THREADS);

	private static void produce () {
		Random r = new Random();
		List<Integer> list = new ArrayList<>();
		int n = r.nextInt(50);
		IntStream.range(0,n).forEach(i -> list.add(r.nextInt(100)));
		
		Product prod = new Product(list);
		futures.add(exec.submit(() -> prod.sum()));
	}
	
	public static void main (String[] args) {
		long start = System.currentTimeMillis();
		IntStream.range(1, 5000).forEach( i -> produce());
		long endProducer = System.currentTimeMillis();
		exec.shutdown();
		try {
			exec.awaitTermination(60, TimeUnit.SECONDS);
		} catch (InterruptedException e) {}
		long endConsumer = System.currentTimeMillis();
		futures.stream().forEach(i -> {
			try {
				System.out.println(i.get());
			} catch (Exception e) {}
		});
		System.out.println("Producer time: " + (endProducer - start));
		System.out.println("Consumer time: " + (endConsumer - start));
		System.out.println("Diff: " + ((endConsumer-start)-(endProducer-start)));
	}
}
